#!/usr/bin/env python3
"""local_executor — run a Shaula task-graph to a deliverable, in-process.

It takes the output of ``workflows.builder.build_plan`` — the vetted,
honesty-preambled, DAG-ordered task graph — and EXECUTES it here against a
pluggable model, fully in-process with no external services. Every non-gate
step:

  * receives its parent steps' outputs as handoff context (the DAG edges);
  * is generated by the model from the task ``body`` (which already carries the
    ``HONESTY_PREAMBLE`` that build_plan prepends to every task);
  * passes through the honesty gate (``gate.lint_gate`` → ``engine/generate.py:
    lint``) before it is accepted — a banned claim parks the whole run, the moat
    holding, never auto-repaired.

The ``requires_review`` / ``triage`` step is a HUMAN gate: the executor parks
the run (``needs_review``) with the template's own ``review-required:`` reason
and never lets the model "approve" it — nothing ships past the honesty review
without a human, identical to the live svc runner's contract.

Scope — honest about what this proves and what it does not:
  * PROVES: the builder bridge, DAG execution with handoffs, the honesty moat
    surviving on real multi-step model output, and a deliverable we can judge
    against the 1-call baseline (``one_call_baseline``).
  * DOES NOT: provide a long-running worker loop, scheduler, or tool runtime
    (web search / skills). It runs the plan once, in-process. Use ``--stub`` for
    a zero-cost, zero-egress offline run.

Pure stdlib + the repo's own modules. No new third-party dependencies.
"""
from __future__ import annotations

import json
import os
import sys
import time
from dataclasses import dataclass, field
from typing import Callable, Optional

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from workflows.builder import (  # noqa: E402
    HONESTY_PREAMBLE,
    PlannedTask,
    WorkflowTemplate,
    build_plan,
    load_template_file,
)
from gate import BrainError, lint_gate  # noqa: E402 — the REAL gate (svc-free, no Vertex call)

# A model is any callable (system, user) -> assistant_text.
Model = Callable[[str, str], str]

_ROLE_SYSTEM = (
    "You are {assignee}, one member of Shaula — the AI office staff of a therapy "
    "practice. Follow the house rules in the task exactly. Return ONLY the "
    "deliverable text for THIS task — no preamble, no sign-off, no meta-commentary."
)


# --------------------------------------------------------------------------- #
# Results
# --------------------------------------------------------------------------- #
@dataclass
class StepResult:
    ref: str
    assignee: str
    title: str
    status: str            # done | parked-review | honesty-failed
    output: str = ""
    seconds: float = 0.0


@dataclass
class RunResult:
    template: str
    topic: str
    status: str            # needs_review | honesty_failed
    steps: list[StepResult] = field(default_factory=list)
    deliverable: str = ""  # the final pre-review artifact (the brief)
    review_reason: str = ""
    honesty: Optional[dict] = None
    seconds: float = 0.0

    def step(self, ref: str) -> Optional[StepResult]:
        return next((s for s in self.steps if s.ref == ref), None)


def _is_human_gate(task: PlannedTask) -> bool:
    """A step the model must never auto-complete (mirrors svc runner SH-F15).

    build_plan folds ``requires_review`` into the task body marker and emits the
    reviewer profile; ``triage`` rides as a payload flag. Any of the three means
    a human owns this step."""
    p = task.payload
    return (
        bool(p.get("triage"))
        or p.get("assignee") == "reviewer"
        or "REQUIRES HUMAN REVIEW" in (p.get("body") or "")
    )


# --------------------------------------------------------------------------- #
# Execution
# --------------------------------------------------------------------------- #
def execute_plan(
    plan: list[PlannedTask],
    model: Model,
    *,
    template_name: str = "",
    topic: str = "",
) -> RunResult:
    """Walk the (already topo-sorted) plan, generate each non-gate step with its
    parent handoffs, honesty-gate every output, and park at the human review."""
    run = RunResult(template=template_name, topic=topic, status="needs_review")
    outputs: dict[str, dict] = {}  # ref -> {"title", "text"}
    t_run = time.time()

    for task in plan:
        ref = task.ref
        p = task.payload
        assignee = p.get("assignee", "")
        title = p.get("title", "")

        if _is_human_gate(task):
            # Every prior step already passed lint_gate, so the package is clean;
            # the human review is the release gate, not a model call.
            verdict = (
                "review-required: clean — every step passed the honesty gate; "
                "held for the clinician's approval before the brief is released."
            )
            run.steps.append(StepResult(ref, assignee, title, "parked-review", verdict))
            run.review_reason = verdict
            run.status = "needs_review"
            break  # nothing past the human review runs

        handoff = "\n\n".join(
            f"--- Handoff from {outputs[d]['title']} ---\n{outputs[d]['text']}"
            for d in task.dep_refs
            if d in outputs
        )
        user = p.get("body", "")
        if handoff:
            user = f"{user}\n\n=== PARENT HANDOFFS ===\n{handoff}"

        t0 = time.time()
        text = model(_ROLE_SYSTEM.format(assignee=assignee), user)
        # THE MOAT — the real gate, never auto-repaired.
        try:
            text = lint_gate(text)
        except BrainError as exc:
            if exc.category == "honesty":
                run.status = "honesty_failed"
                run.honesty = {
                    "atRef": ref,
                    "detail": exc.detail,
                    "reasons": list(getattr(exc, "explanations", []) or []),
                }
                run.steps.append(
                    StepResult(ref, assignee, title, "honesty-failed", "", time.time() - t0)
                )
                run.seconds = time.time() - t_run
                return run
            raise

        outputs[ref] = {"title": title, "text": text}
        run.steps.append(StepResult(ref, assignee, title, "done", text, time.time() - t0))

    brief = run.step("brief")
    if brief and brief.status == "done":
        run.deliverable = brief.output
    else:
        run.deliverable = next(
            (s.output for s in reversed(run.steps) if s.status == "done"), ""
        )
    run.seconds = time.time() - t_run
    return run


def run_template_file(
    path: str,
    variables: dict[str, str],
    model: Model,
    *,
    allow_phi: bool = False,
) -> RunResult:
    """Load a capability template, build its task-graph, and execute it."""
    tmpl: WorkflowTemplate = load_template_file(path)
    plan = build_plan(tmpl, variables, allow_phi=allow_phi)
    return execute_plan(
        plan, model, template_name=tmpl.name, topic=variables.get("topic", "")
    )


# --------------------------------------------------------------------------- #
# Baseline — the 1-call straw-man the multi-step graph is measured against
# --------------------------------------------------------------------------- #
def one_call_baseline(topic: str, project: str, model: Model) -> str:
    """A single model call asking for the whole brief at once — the naive path
    the multi-step task-graph must beat. Same honesty gate applies."""
    system = _ROLE_SYSTEM.format(assignee="blog")
    user = (
        HONESTY_PREAMBLE
        + f'Write one complete, clinician-ready research brief on "{topic}" for '
        f"the {project} practice, drawing only on your own general knowledge "
        "(you have no web search). Include: a plain-language summary; key "
        "findings each tagged [established], [commonly described], or "
        "[unverified]; practical considerations framed as considerations to "
        "weigh (never recommendations); open questions; a verification checklist "
        "of every named source; and a closing disclaimer that this is "
        "informational background, not clinical advice. Invent no statistic and "
        "no citation you cannot personally verify. Return only the brief."
    )
    return lint_gate(model(system, user))
